version: '3.8'

services:
  vue-list-manager-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=/api
    restart: always
